# CITE-seq prediction for OpenProblems data format

In this example, we'll apply the best CITE-seq prediction model to the data format of the [modality prediction task](https://openproblems.bio/benchmarks/predict_modality?version=v1.0.0) in [OpenProblems](https://openproblems.bio/). For a general and a more detailed example, take a look at `example.ipynb`

In [1]:
import logging

import mudata as mu
import numpy as np
import scanpy as sc

from senkin_tmp_cite_pred.preprocess import preprocess_data

/Users/vladimir.shitov/miniconda3/envs/2025_08_citeseqpred/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Create directories for data and models:

In [2]:
logging.basicConfig(level=logging.DEBUG)

In [3]:
%%bash

mkdir -p data/
mkdir -p models/

DEBUG:asyncio:Using selector: KqueueSelector

In [4]:
adata_rna_train = sc.read_h5ad("data/train_mod1.h5ad")
adata_rna_test = sc.read_h5ad("data/test_mod1.h5ad")
adata_prot_train = sc.read_h5ad("data/train_mod2.h5ad")
adata_prot_test = sc.read_h5ad("data/test_mod2.h5ad")

DEBUG:h5py._conv:Creating converter from 3 to 5

In [5]:
adata_rna_train.shape, adata_rna_test.shape, adata_prot_train.shape, adata_prot_test.shape

((431, 134), (163, 134), (431, 134), (163, 134))

In the 2022 competition, the batch effect correction for this approach was done per day. Let's follow that, and extract day in a separate `.obs` column:

In [6]:
adata_rna_test.obs

                         size_factors batch
TCCGAAAAGAGGACTC-1-s4d8          22.0  s4d8
ATTCATCGTTAGTCGT-1-s4d1          15.0  s4d1
CATCGTCTCTGAGAGG-1-s4d8          23.0  s4d8
CATGGATGTACGCTAT-1-s4d1           7.0  s4d1
TCCTTCTTCCACCCTA-1-s2d1          15.0  s2d1
...                               ...   ...
CATTCCGAGTGCTACT-1-s4d8          30.0  s4d8
AATGGAATCCATTCAT-1-s4d8          39.0  s4d8
GGCTTTCGTGGACCTC-1-s4d8          51.0  s4d8
GTGGTTAAGCATAGGC-1-s3d7          12.0  s3d7
GAGGCAATCTCCAAGA-1-s4d1          52.0  s4d1

[163 rows x 2 columns]

In [7]:
def extract_day_and_donor_from_batch(batch: str) -> tuple[str, str]:
    "Extract day and donor numbers N and M from IDs of format sNdM"
    d_index = batch.find("d")
    day = batch[1: d_index]
    donor = batch[d_index + 1 :]
    return day, donor

adata_rna_train.obs["day"], adata_rna_train.obs["donor"] = zip(*adata_rna_train.obs["batch"].astype(str).map(extract_day_and_donor_from_batch))
adata_rna_test.obs["day"], adata_rna_test.obs["donor"] = zip(*adata_rna_test.obs["batch"].astype(str).map(extract_day_and_donor_from_batch))
adata_prot_train.obs["day"], adata_prot_train.obs["donor"] = zip(*adata_prot_train.obs["batch"].astype(str).map(extract_day_and_donor_from_batch))
adata_prot_test.obs["day"], adata_prot_test.obs["donor"] = zip(*adata_prot_test.obs["batch"].astype(str).map(extract_day_and_donor_from_batch))

In [8]:
adata_rna_train.obs["split"] = "train"
adata_rna_test.obs["split"] = "test"
adata_prot_train.obs["split"] = "train"
adata_prot_test.obs["split"] = "test"

Put all the modalities in one object. This will make sure that the indexes are aligned

In [9]:
adata_rna_train.var

                  hvg  hvg_score
ENSG00000104320  True  -0.674490
ENSG00000187713  True  -0.251418
ENSG00000260349  True   0.391433
ENSG00000150756  True  -0.720957
ENSG00000105676  True  -0.674490
...               ...        ...
ENSG00000241343  True  -4.003093
ENSG00000196267  True   0.000000
ENSG00000112078  True   0.686500
ENSG00000261136  True  -0.698529
ENSG00000163848  True  -0.103547

[134 rows x 2 columns]

In [10]:
mdata = mu.MuData({"rna": sc.concat([adata_rna_train, adata_rna_test], axis=0), "prot": sc.concat([adata_prot_train, adata_prot_test], axis=0)})
mdata

/Users/vladimir.shitov/miniconda3/envs/2025_08_citeseqpred/lib/python3.13/site-packages/mudata/_core/mudata.py:1598: FutureWarning: From 0.4 .update() will not pull obs/var columns from individual modalities by default anymore. Set mudata.set_options(pull_on_update=False) to adopt the new behaviour, which will become the default. Use new pull_obs/pull_var and push_obs/push_var methods for more flexibility.
  self._update_attr("var", axis=0, join_common=join_common)
/Users/vladimir.shitov/miniconda3/envs/2025_08_citeseqpred/lib/python3.13/site-packages/mudata/_core/mudata.py:963: UserWarning: Cannot join columns with the same name because var_names are intersecting.
  warnings.warn(
/Users/vladimir.shitov/miniconda3/envs/2025_08_citeseqpred/lib/python3.13/site-packages/mudata/_core/mudata.py:1461: FutureWarning: From 0.4 .update() will not pull obs/var columns from individual modalities by default anymore. Set mudata.set_options(pull_on_update=False) to adopt the new behaviour, which will become the default. Use new pull_obs/pull_var and push_obs/push_var methods for more flexibility.
  self._update_attr("obs", axis=1, join_common=join_common)

MuData object with n_obs × n_vars = 594 × 268
  2 modalities
    rna:	594 x 134
      obs:	'size_factors', 'batch', 'day', 'donor', 'split'
      layers:	'counts', 'normalized'
    prot:	594 x 134
      obs:	'size_factors', 'batch', 'day', 'donor', 'split'
      layers:	'counts', 'normalized'

We can add a set of known features, which are important for prediction of the given surface proteins. In the original solution, it was a set of genes that encode proteins in the CITE-seq data. Here, we'll use genes that encoded proteins used **in the 2022 competition**. Make sure to select these features appropriately, this is very important! Additionally, double check that IDs have an appropriate format: same type of encoding, no suffixes, etc.

In [11]:
competition_2022_genes = [
    "ENSG00000134256",
    "ENSG00000083457",
    "ENSG00000185896",
    "ENSG00000130202",
    "ENSG00000182578",
    "ENSG00000027697",
    "ENSG00000005844",
    "ENSG00000169896",
    "ENSG00000140678",
    "ENSG00000100385",
    "ENSG00000185291",
    "ENSG00000292332",
    "ENSG00000077238",
    "ENSG00000168685",
    "ENSG00000166825",
    "ENSG00000186827",
    "ENSG00000049249",
    "ENSG00000131495",
    "ENSG00000170458",
    "ENSG00000178726",
    "ENSG00000117525",
    "ENSG00000076706",
    "ENSG00000163599",
    "ENSG00000102245",
    "ENSG00000073008",
    "ENSG00000274108",
    "ENSG00000283708",
    "ENSG00000284241",
    "ENSG00000275623",
    "ENSG00000277317",
    "ENSG00000284236",
    "ENSG00000274410",
    "ENSG00000275008",
    "ENSG00000283702",
    "ENSG00000277484",
    "ENSG00000274830",
    "ENSG00000284044",
    "ENSG00000276590",
    "ENSG00000284510",
    "ENSG00000243772",
    "ENSG00000274952",
    "ENSG00000277924",
    "ENSG00000284333",
    "ENSG00000284132",
    "ENSG00000283996",
    "ENSG00000276218",
    "ENSG00000277554",
    "ENSG00000278327",
    "ENSG00000284504",
    "ENSG00000283790",
    "ENSG00000274402",
    "ENSG00000273947",
    "ENSG00000273887",
    "ENSG00000276459",
    "ENSG00000278369",
    "ENSG00000275658",
    "ENSG00000276011",
    "ENSG00000275914",
    "ENSG00000278731",
    "ENSG00000278692",
    "ENSG00000275546",
    "ENSG00000274412",
    "ENSG00000277725",
    "ENSG00000277251",
    "ENSG00000276731",
    "ENSG00000273661",
    "ENSG00000273578",
    "ENSG00000275960",
    "ENSG00000274518",
    "ENSG00000275452",
    "ENSG00000275735",
    "ENSG00000278300",
    "ENSG00000274438",
    "ENSG00000275253",
    "ENSG00000276425",
    "ENSG00000276139",
    "ENSG00000276258",
    "ENSG00000277885",
    "ENSG00000278152",
    "ENSG00000275737",
    "ENSG00000274948",
    "ENSG00000273775",
    "ENSG00000283731",
    "ENSG00000284093",
    "ENSG00000274036",
    "ENSG00000274920",
    "ENSG00000284426",
    "ENSG00000276329",
    "ENSG00000275717",
    "ENSG00000276423",
    "ENSG00000284177",
    "ENSG00000284589",
    "ENSG00000284342",
    "ENSG00000275659",
    "ENSG00000276379",
    "ENSG00000275786",
    "ENSG00000275486",
    "ENSG00000283827",
    "ENSG00000278079",
    "ENSG00000277175",
    "ENSG00000278856",
    "ENSG00000276501",
    "ENSG00000273518",
    "ENSG00000275545",
    "ENSG00000278368",
    "ENSG00000167633",
    "ENSG00000277272",
    "ENSG00000274146",
    "ENSG00000278427",
    "ENSG00000283954",
    "ENSG00000283729",
    "ENSG00000275288",
    "ENSG00000203747",
    "ENSG00000162747",
    "ENSG00000111796",
    "ENSG00000110876",
    "ENSG00000177575",
    "ENSG00000088827",
    "ENSG00000198053",
    "ENSG00000160255",
    "ENSG00000160683",
    "ENSG00000177455",
    "ENSG00000121807",
    "ENSG00000183813",
    "ENSG00000160791",
    "ENSG00000112486",
    "ENSG00000158481",
    "ENSG00000158473",
    "ENSG00000116824",
    "ENSG00000171431",
    "ENSG00000263057",
    "ENSG00000156738",
    "ENSG00000117322",
    "ENSG00000012124",
    "ENSG00000089692",
    "ENSG00000100031",
    "ENSG00000150637",
    "ENSG00000104921",
    "ENSG00000272398",
    "ENSG00000122223",
    "ENSG00000172183",
    "ENSG00000134460",
    "ENSG00000197635",
    "ENSG00000159958",
    "ENSG00000139193",
    "ENSG00000157873",
    "ENSG00000273936",
    "ENSG00000186265",
    "ENSG00000120217",
    "ENSG00000163600",
    "ENSG00000276977",
    "ENSG00000188389",
    "ENSG00000178562",
    "ENSG00000150093",
    "ENSG00000198178",
    "ENSG00000099250",
    "ENSG00000261371",
    "ENSG00000213809",
    "ENSG00000026751",
    "ENSG00000072694",
    "ENSG00000143226",
    "ENSG00000168995",
    "ENSG00000105383",
    "ENSG00000275521",
    "ENSG00000273916",
    "ENSG00000277442",
    "ENSG00000273506",
    "ENSG00000276450",
    "ENSG00000277824",
    "ENSG00000278362",
    "ENSG00000278025",
    "ENSG00000275637",
    "ENSG00000275822",
    "ENSG00000274053",
    "ENSG00000277629",
    "ENSG00000189430",
    "ENSG00000275156",
    "ENSG00000273535",
    "ENSG00000277334",
    "ENSG00000203710",
    "ENSG00000162739",
    "ENSG00000135218",
    "ENSG00000004468",
    "ENSG00000138185",
    "ENSG00000010610",
    "ENSG00000101017",
    "ENSG00000005961",
    "ENSG00000185245",
    "ENSG00000026508",
    "ENSG00000262418",
    "ENSG00000081237",
    "ENSG00000196776",
    "ENSG00000117091",
    "ENSG00000213949",
    "ENSG00000164171",
    "ENSG00000115232",
    "ENSG00000091409",
    "ENSG00000110448",
    "ENSG00000169442",
    "ENSG00000090339",
    "ENSG00000149294",
    "ENSG00000109956",
    "ENSG00000116815",
    "ENSG00000188404",
    "ENSG00000174175",
    "ENSG00000135404",
    "ENSG00000150337",
    "ENSG00000110848",
    "ENSG00000173762",
    "ENSG00000072274",
    "ENSG00000137101",
    "ENSG00000135318",
    "ENSG00000007312",
    "ENSG00000153563",
    "ENSG00000110651",
    "ENSG00000085117",
    "ENSG00000112149",
    "ENSG00000276452",
    "ENSG00000274669",
    "ENSG00000277134",
    "ENSG00000104972",
    "ENSG00000277807",
    "ENSG00000114013",
    "ENSG00000197405",
    "ENSG00000010278",
    "ENSG00000125810",
    "ENSG00000134539",
    "ENSG00000026103",
    "ENSG00000168329",
    "ENSG00000179639",
    "ENSG00000291905",
    "ENSG00000206493",
    "ENSG00000225201",
    "ENSG00000233904",
    "ENSG00000230254",
    "ENSG00000236632",
    "ENSG00000229252",
    "ENSG00000204592",
    "ENSG00000102245",
    "ENSG00000139187",
    "ENSG00000205274",
    "ENSG00000181847",
]

In [12]:
known_features = np.intersect1d(competition_2022_genes, mdata.mod["rna"].var_names)
print(f"Number of proteins with identical names in RNA: {len(known_features)}")

Number of proteins with identical names in RNA: 1

Now we can perform required preprocessing with just one function. It includes:
- Removal of constant features
- 200 components TSVD of CLR-transformed data
- 100 components PCA of customly normalized data (see documentation of `senkin_normalize` for details)
- Selection of raw expression for known features and for genes correlated with target proteins
- DSB normalization of protein data. For this `empty_count_range` setting is needed. Here, we used the same values as in 2022 competition. But this is data dependent, so make sure to select a meaningful range!

Note that the nomber of cells will become smaller after this step, because some droplets will be used as a background for DSB normalization. Additionally, number of genes will decrease as constant genes will be removed from RNA data.

In [13]:
import logging
logging.basicConfig(level=logging.DEBUG)

Put raw counts in .X for both modalities:

In [14]:
mdata.mod["rna"].X = mdata.mod["rna"].layers["counts"]
mdata.mod["prot"].X = mdata.mod["prot"].layers["counts"]

In [15]:
mdata = preprocess_data(
    mdata,
    empty_counts_range=(0., 1.),  # Note that this is data-dependent! Data must contain empty droplets.
    batch_key="day",
    group_key="donor",
    known_features=known_features
)

INFO:senkin_tmp_cite_pred.preprocess:DSB-normalizing protein data. The number of cells will be reduced.
DEBUG:senkin_tmp_cite_pred.preprocess:Number of cells before DSB: 594
/Users/vladimir.shitov/miniconda3/envs/2025_08_citeseqpred/lib/python3.13/site-packages/mudata/_core/mudata.py:1598: FutureWarning: From 0.4 .update() will not pull obs/var columns from individual modalities by default anymore. Set mudata.set_options(pull_on_update=False) to adopt the new behaviour, which will become the default. Use new pull_obs/pull_var and push_obs/push_var methods for more flexibility.
  self._update_attr("var", axis=0, join_common=join_common)
/Users/vladimir.shitov/miniconda3/envs/2025_08_citeseqpred/lib/python3.13/site-packages/mudata/_core/mudata.py:963: UserWarning: Cannot join columns with the same name because var_names are intersecting.
  warnings.warn(
/Users/vladimir.shitov/miniconda3/envs/2025_08_citeseqpred/lib/python3.13/site-packages/mudata/_core/mudata.py:1461: FutureWarning: From 0.4 .update() will not pull obs/var columns from individual modalities by default anymore. Set mudata.set_options(pull_on_update=False) to adopt the new behaviour, which will become the default. Use new pull_obs/pull_var and push_obs/push_var methods for more flexibility.
  self._update_attr("obs", axis=1, join_common=join_common)
DEBUG:senkin_tmp_cite_pred.preprocess:Number of cells after DSB: 507
INFO:senkin_tmp_cite_pred.preprocess:Starting RNA preprocessing
INFO:senkin_tmp_cite_pred.preprocess:Normalization and log1p-transformation
INFO:senkin_tmp_cite_pred.preprocess:Removing constant variables
INFO:senkin_tmp_cite_pred.preprocess:Computing CLR-TSVD transformation with 200 components
/Users/vladimir.shitov/miniconda3/envs/2025_08_citeseqpred/lib/python3.13/site-packages/muon/_prot/preproc.py:219: UserWarning: adata.X is sparse but not in CSC format. Converting to CSC.
  warn("adata.X is sparse but not in CSC format. Converting to CSC.")
INFO:senkin_tmp_cite_pred.preprocess:Applying Senkin normalization
/Users/vladimir.shitov/miniconda3/envs/2025_08_citeseqpred/lib/python3.13/site-packages/anndata/_core/aligned_mapping.py:284: ImplicitModificationWarning: Obsm 'X_sqrt_norm' should not be a np.matrix, use np.ndarray instead.
  return super()._validate_value(val, key)
INFO:senkin_tmp_cite_pred.preprocess:Computing PCA with 100 components
INFO:senkin_tmp_cite_pred.preprocess:Verifying observation names match between RNA and protein data
INFO:senkin_tmp_cite_pred.preprocess:Selecting features based on known proteins and correlations
/Users/vladimir.shitov/Documents/programming/senin_tmp_CITE_pred/senkin-tmp-cite-pred/senkin_tmp_cite_pred/preprocess.py:27: RuntimeWarning: invalid value encountered in divide
  X = (X - X.mean(axis=0)) / X.std(axis=0)
INFO:senkin_tmp_cite_pred.preprocess:Found 118 top correlated genes
INFO:senkin_tmp_cite_pred.preprocess:Total 118 features selected
INFO:senkin_tmp_cite_pred.preprocess:RNA preprocessing completed

Note new `obsm` fields in RNA modality, and a `dsb` layer in the protein modality:

In [16]:
mdata

MuData object with n_obs × n_vars = 507 × 268
  2 modalities
    rna:	507 x 134
      obs:	'size_factors', 'batch', 'day', 'donor', 'split'
      uns:	'log1p', 'selected_features'
      obsm:	'X_log_normalized', 'X_clr_tsvd', 'X_sqrt_norm', 'X_pca_sqrt_norm', 'X_raw_selected'
      layers:	'counts', 'normalized'
    prot:	507 x 134
      obs:	'size_factors', 'batch', 'day', 'donor', 'split'
      layers:	'counts', 'normalized', 'dsb'

# LGBM predictions

Next, we'll use preprocessed data to make initial prediction of target proteints with Light Gradient Bossting (LGBM) models. The dimensionality of the predictions will be further reduced with TSVD to 100 components. While these predictions are not used per se, they will become features for neural networks. As we showed in our analysis, this makes the resulting prediction much more accurate.

In [17]:
from senkin_tmp_cite_pred.lgbm_models import train_lightgbm_models
from sklearn.model_selection import KFold

In [18]:
adata_rna = mdata.mod["rna"]
adata_rna

AnnData object with n_obs × n_vars = 507 × 134
    obs: 'size_factors', 'batch', 'day', 'donor', 'split'
    uns: 'log1p', 'selected_features'
    obsm: 'X_log_normalized', 'X_clr_tsvd', 'X_sqrt_norm', 'X_pca_sqrt_norm', 'X_raw_selected'
    layers: 'counts', 'normalized'

In [19]:
adata_prot = mdata.mod["prot"]
adata_prot

AnnData object with n_obs × n_vars = 507 × 134
    obs: 'size_factors', 'batch', 'day', 'donor', 'split'
    layers: 'counts', 'normalized', 'dsb'

In [20]:
adata_rna.obs["day"].value_counts()

day
2    147
3    145
4    112
1    103
Name: count, dtype: int64

In [21]:
adata_rna.obs["split"].value_counts()

split
train    353
test     154
Name: count, dtype: int64

Additionally, we'll define cross-validation splits for the training dataset. It'll help us to see how well our models predict the data on an unseen fold. In this example we'll use 2 folds because we have a very small dataset for testing. In the original approach, 5 folds CV was used. **Set `n_splits` to 5 to match the original approach**

In [22]:
folds = KFold(n_splits=2, shuffle=True, random_state=666)

We'll save which cell comes from each fold to make sure results are reproducible after the `folds` variable is lost:

In [23]:
for i, (train_idxs, test_idxs) in enumerate(folds.split(adata_rna)):
    adata_rna.obs[f"fold_{i}"] = "test"
    adata_rna.obs.loc[adata_rna.obs_names[train_idxs], f"fold_{i}"] = "train"

adata_rna.obs["fold_0"].value_counts()

fold_0
test     254
train    253
Name: count, dtype: int64

In [24]:
train_cell_ids = adata_rna.obs_names[adata_rna.obs["split"] == "train"]
test_cell_ids = adata_rna.obs_names[adata_rna.obs["split"] == "test"]

Train LGBM models. 4 models will be trained, using different subsets of training data, and different preprocessing of the target proteins. Remove `num_boost_round`, `early_stopping_rounds`, and `n_tsvd_components` to use the default parameters

In [25]:
adata_rna = train_lightgbm_models(
    adata_rna,
    adata_prot,
    train_cell_ids=train_cell_ids,
    test_cell_ids=test_cell_ids,
    folds=folds,
    num_boost_round=3,
    early_stopping_rounds=2,
    n_tsvd_components=10
)

INFO:senkin_tmp_cite_pred.lgbm_models:Initializing arrays in obsm with zeros
INFO:senkin_tmp_cite_pred.lgbm_models:Training LightGBM models
INFO:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model 1 for predicting DSB-normalized protein expression from log-normalized RNA expression
INFO:senkin_tmp_cite_pred.lgbm_models:Training LightGBM models for 134 targets
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 2
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 3
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 4
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 5
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 6
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 7
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 8
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 9
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 10
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.306131
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.25919
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.63054
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.651309
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.213915
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.337791
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.590747
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.901736
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 5.53696
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 3.11327
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.15066
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.31308
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 9.41891
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 8.99286
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.953309
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.53484
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.527386
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.387878
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.43628
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.966303
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.97465

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 11
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 12
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 13
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 14
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 15
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 16
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 17
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 18
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 19
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 20
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.13865
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.640429
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.557705
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.243259
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.440273
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.87413
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 2.07777
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.93071
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.85096
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 12.4594
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 7.83852
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.451396
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.595148
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.681792
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.95843
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.90642
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 5.15199
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 3.40352
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.80896
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.687789
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.007

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 21
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 22
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 23
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 24
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 25
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 26
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 27
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 28
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 29
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 30
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 31
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 32
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 33

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.33107
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 5.78207
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.53258
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.73873
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.0386
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.95108
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.914879
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.70398
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.462267
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.31359
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.36637
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.36177
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.24745
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.72964
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.5235
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.66773
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.38226
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.59118
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 2.04326
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.06949
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.713099
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.920304
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.06169
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.978621

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 34
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 35
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 36
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 37
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 38
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 39
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 40
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 41
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 42
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 43
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 44
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 45
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.544397
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.660708
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.392424
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.350891
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.0851
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.26488
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.402639
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.469345
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.3444
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 3.71988
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.59552
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.44551
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.61308
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 2.96221
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.325358
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.299798
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 5.67248
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 6.96506
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.611184
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.831844
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.429228
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.338144
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.31169
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.25187
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.382737

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 46
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 47
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 48
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 49
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 50
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 51
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 52
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 53
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 54
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 55
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 56
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 57
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 58
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.437929
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.57524
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.6326
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.249942
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.39649
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.488034
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.286021
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.10981
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.30632
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.907854
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.30389
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.639907
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.629288
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.45432
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 7.00325
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.456289
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.618574
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 5.52748
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 4.83518
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.82363
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.50301
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.523232
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.738316
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.485075
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.773443

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 59
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 60
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 61
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 62
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 63
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 64
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 65
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 66
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 67
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 68
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.610504
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.798528
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 24.8289
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 12.5539
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.337814
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.546938
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.960559
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.00063
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.81757
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.59596
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.74552
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.20813
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.421581
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.32604
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.327271
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.272981
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.24432
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.927455
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.427307
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.536442
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.84341

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 69
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 70
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 71
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 72
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 73
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 74
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 75
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 76
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 77
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 78
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.42853
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.71946
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.87896
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.633226
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.652154
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.596366
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.515049
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 11.9971
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 8.5968
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.16714
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.26439
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.80495
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.59393
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.21115
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.759794
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.28883
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 4.91837
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.320614
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.38747
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.403099
Training until validation scores don't improve for 2 rounds

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 79
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 80
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 81
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 82
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 83
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 84
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 85
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 86
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 87
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 88
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Early stopping, best iteration is:
[1]	valid_0's l2: 0.377658
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.455189
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.441394
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.59938
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.93038
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.11597
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.86507
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.898575
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.93998
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 13.1479
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 13.6231
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.48952
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.37412
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.14031
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.2042
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.06747
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.45199
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.70427
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 3.22592
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.64481

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 89
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 90
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 91
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 92
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 93
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 94
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 95
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 96
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 97
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 98
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 99
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 2.60573
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.316976
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.318179
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.34357
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.12916
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.3246
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.4036
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.82713
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.17504
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.40118
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.33932
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.35214
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.333575
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 21.0372
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 8.76891
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.38609
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.35706
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 5.91657
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 4.45303
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.90362
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.9619

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 100
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 101
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 102
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 103
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 104
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 105
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 106
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 107
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 108
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 109
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.39867
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.967885
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 6.4995
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 6.14467
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.355335
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.334889
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.83148
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.20914
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.38533
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.53075
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.60944
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 4.44577
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.411925
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.432956
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.911361
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.30436
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.257398
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.34766
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 2.60748
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 2.55191
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.721777

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 110
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 111
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 112
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 113
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 114
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 115
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 116
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 117
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 118
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 119

Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.14227
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.97826
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 3.22508
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.47906
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.596287
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.72496
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 2.76848
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.380504
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.377567
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 5.18047
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 4.68674
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.86151
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.03385
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.42133
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.447493
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.539561
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.910722
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.968369
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.15599

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 120
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 121
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 122
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 123
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 124
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 125
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 126
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 127
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 128
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 129

Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.52479
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.67676
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.605306
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.49203
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.06745
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.53316
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.39685
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 3.50952
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.840621
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.03589
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.285624
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.343493
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 3.05455
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.74512
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.4556
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 5.38341
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.34343
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.865487
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.29368
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.12463

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 130
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 131
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 132
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 133
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
INFO:senkin_tmp_cite_pred.lgbm_models:CV score: 0.27036278535158226
INFO:senkin_tmp_cite_pred.lgbm_models:TSVD-reducing predictions to 10 components
INFO:senkin_tmp_cite_pred.lgbm_models:Preparing datasets for LightGBM model 2
INFO:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model 2 for predicting DSB-normalized protein expression from customly normalized RNA expression data and selected features
INFO:senkin_tmp_cite_pred.lgbm_models:Training LightGBM models for 134 targets
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.02237
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.56384
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.326922
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.456627
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.438082
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.377543
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.24363
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.99355
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.52384
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 2.29092
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.306127
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.259187
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.63095

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 2
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 3
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 4
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 5
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 6
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.651358
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.212374
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.337259
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.5896
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.899718
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 5.5352
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.1072
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.1352
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.29571

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 7
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 8
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 9
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 10
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 11
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 9.42235
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 8.98088
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.945719
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.52556
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.527368
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.387858
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.43455
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.965028
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.9594
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.12418

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 12
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 13
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 14
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 15
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 16
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.640375
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.556364
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.241214
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.437658
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.84176
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.04301
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.89683
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.81359
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 12.4551
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 7.82309

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 17
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 18
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 19
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 20
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 21
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.451442
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.594459
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.674862
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.949329
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.8354
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 5.08757
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.39822
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.80844
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.683862
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.00139

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 22
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 23
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 24
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 25
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 26
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.33529
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 5.78127
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.50541
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.70869
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.02907
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.93783
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.915488
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.69826
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.459691
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.31303

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 27
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 28
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 29
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 30
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 31
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.35006
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.34416
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.24828
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.72241
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.52358
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.668161
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.37517
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.57963
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.04241
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.06855
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.713645

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 32
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 33
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 34
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 35
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 36
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.9188
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.05088
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.967814
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.542538
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.65875
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.392503
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.350624
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.0696
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.24593
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.40294

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 37
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 38
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 39
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 40
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 41
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.468229
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.30624
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.6778
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.5941
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.44141
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 2.61263
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.95145
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.325235
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.299643

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 42
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 43
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 44
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 45
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 5.65258
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 6.96228
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.607535
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.83139
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.428993
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.337887
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.30947
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.24264
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.382593
Training until validation scores don't improve for 2 rounds

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 46
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 47
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 48
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 49
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 50
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 51
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.436851
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.55837
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.61421
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.247251
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.393458
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.487283
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.285849
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.10486
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.29479
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.907544
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.29768

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 52
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 53
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 54
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 55
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.634226
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.622307
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.45146
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 6.99867
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.451928
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.613353
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 5.49794
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.79809
Training until validation scores don't improve for 2 rounds

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 56
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 57
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 58
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 59
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 60
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.79201
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.47061
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.513047
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.730665
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.477468
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.763779
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.604542
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.792215
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 24.7818
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 12.5194
Training until validation scores don't improve for 2 rounds

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 61
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 62
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 63
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 64
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 65
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.336304
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.544566
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.935816
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.980463
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.81562
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.59499
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.74452
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.19705
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.421767
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.325984
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.327846

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 66
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 67
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 68
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 69
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 70
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.272591
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.24126
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.921918
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.426827
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.536637
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.841919
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.42767
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.71832
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.87577

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 71
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 72
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 73
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 74
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 75
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.633721
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.652263
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.593781
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.510263
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 11.9889
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 8.58391
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.16045
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.2497
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.7912
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.58613

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 76
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 77
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 78
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 79
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 80
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.21024
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.757704
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.25178
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.8866
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.319775
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.385912
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.400044
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.374856
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.455785
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.441322

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 81
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 82
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 83
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 84
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 85
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.59052
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.92301
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.11431
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.86606
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.899417
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.93737
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 13.0025
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 13.4851
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.48749
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.37354

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 86
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 87
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 88
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 89
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 90
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.13669
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.20017
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.06159
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.44705
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.70247
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.22057
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.64144
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 2.60315
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.317822
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.316702

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 91
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 92
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 93
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 94
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 95
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.3407
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.12714
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.32483
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.40342
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.80798
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.15144
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.4004
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.33796
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.35196
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.33359

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 96
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 97
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 98
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 99
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 100
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 21.0138
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 8.75719
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.386258
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.357167
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 5.91449
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 4.44049
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.87695
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.93765
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.39815
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.967692
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 6.41224

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 101
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 102
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 103
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 104
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 105
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 6.0418
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.355079
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.334797
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.80502
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.18053
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.38371
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.5255
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.5388
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.37511
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.412313

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 106
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 107
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 108
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 109
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 110
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 111

Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.433772
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.899736
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.28679
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.256621
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.347762
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.60422
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.53206
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.716395
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.13717
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.96218
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.21977

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 112
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 113
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 114
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 115
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 116
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.478875
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.596008
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.69852
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.72498
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.380187
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.377399
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 5.13446
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.6344
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.84208
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.0093
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.420596

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 117
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 118
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 119
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 120
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 121
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.446994
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.534521
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.904418
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.967713
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.15377
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.52276
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.67505
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.596563
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.48537
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.04389

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 122
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 123
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 124
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 125
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 126
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 127
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.50455
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.36647
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.47419
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.8403
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.03354
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.285361
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.342925
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.04925
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.73496
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.39261
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 5.32615

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 128
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 129
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 130
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 131
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 132
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.34384
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.8661
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.29193
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.11589
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.00983
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.54541
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.321906
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.45014
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.43787
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.376972
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.23603

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 133
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
INFO:senkin_tmp_cite_pred.lgbm_models:CV score: 0.2753610466751366
INFO:senkin_tmp_cite_pred.lgbm_models:TSVD-reducing predictions to 10 components
INFO:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model 3 for predicting DSB-normalized protein expression from raw RNA expression
INFO:senkin_tmp_cite_pred.lgbm_models:Training LightGBM models for 134 targets
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 2
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 3
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 4
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 5
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.97512
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.51573
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.28235
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.306165
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.259097
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.63074
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.651139
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.213978
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.3375
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.591233
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.900857
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 5.53591
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.1125
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.15128

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 6
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 7
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 8
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 9
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 10
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 11
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 12
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 13
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 14
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 15
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 16
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.31067
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 9.42035
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 8.98674
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.956243
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.53359
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.527403
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.38788
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.43646
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.965472
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.97526
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.13293
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.640435
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.557605
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.24344
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.440193
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.87375
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.07181
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.93108
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.84195
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 12.462
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 7.82995

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 17
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 18
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 19
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 20
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 21
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 22
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 23
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 24
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 25
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 26
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.451419
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.595253
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.683882
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.956979
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.91254
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 5.13876
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.40291
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.80712
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.689366
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.00564
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.33335
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 5.78022
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.53235
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.73402
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.03963
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.95118
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.916294
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.70393
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.462312
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.31326
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.3709

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 27
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 28
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 29
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 30
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 31
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 32
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 33
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 34
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 35
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 36
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.35853
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.24955
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.73114
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.52401
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.667715
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.38237
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.59066
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 2.04196
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.06856
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.713743
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.919806
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.06159
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.977955
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.544242
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.660681
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.392573
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.350619
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.08641
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.26192
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.402747

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 37
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 38
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 39
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 40
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 41
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 42
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 43
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 44
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 45
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 46
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.469153
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 4.34565
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.71216
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.59723
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.44462
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.61404
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.9605
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.325376
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.299839
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 5.67779
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 6.95818
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.61144
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.831611
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.429457
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.338301
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 2.31266
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.25096
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.382727
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.437685
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.57637

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 47
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 48
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 49
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 50
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 51
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 52
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 53
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 54
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 55
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 56
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.62739
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.249774
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.395875
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.488224
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.285902
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.11191
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.30471
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.910159
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.30431
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.639368
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.62858
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.45545
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 7.00101
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.456858
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.618263
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 5.53117
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.82473
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 2.82767
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.49166
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.523451

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 57
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 58
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 59
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 60
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 61
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 62
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 63
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 64
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 65
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 66
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 67
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.737375
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.485584
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.772497
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.611505
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.79743
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 24.8344
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 12.5426
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.337707
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.546518
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.960329
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.998396
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.81645
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.59632
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 4.74789
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.20563
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.421809
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.326014
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.327577
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.273055
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.24449
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.926935
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.427818

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 68
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 69
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 70
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 71
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 72
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 73
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 74
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 75
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 76
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 77
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.536181
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.843155
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.42796
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 2.71995
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.87655
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.633664
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.652138
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.59691
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.513881
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 11.9982
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 8.59041
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.171
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.2606
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.80473
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.59258
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.2115
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.759963
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 4.28986
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.90585
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.320885

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 78
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 79
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 80
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 81
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 82
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 83
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 84
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 85
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 86
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 87
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 88
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.3869
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.403675
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.377483
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.455443
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.441269
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 2.59953
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.93054
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.11716
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.86466
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.89864
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.94044
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 13.1571
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 13.5814
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.49009
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.37336
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.14239
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.2029
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.06795
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.45193
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.70431
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.2246

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 89
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 90
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 91
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 92
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 93
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 94
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 95
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 96
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 97
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 98
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.64563
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.60363
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.317268
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.318133
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.34349
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.12887
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.32438
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.40339
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.82946
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.16789
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.40139
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.33933
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.352041
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.33374
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 21.0374
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 8.76337
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.386166
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.35711
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 5.91963
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.44969
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.90387

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 99
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 100
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 101
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 102
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 103
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 104
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 105
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 106
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 107
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 108
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.95962
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.39924
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.966513
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 6.50949
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 6.12349
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.355536
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.33496
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.83479
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.2053
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.38474
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.52958
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.61539
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.43432
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.412111
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.433077
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.913286
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.30397
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.257457
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.347757

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 109
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 110
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 111
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 112
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 113
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 114
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 115
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 116
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 117
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 2.60725
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.55188
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.722535
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.14125
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 3.97953
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 3.22441
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.479093
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.596074
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 2.72809
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.76452
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.380662
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.377516
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 5.18565
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.67418
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.86505
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.02915
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.421277
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.447324

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 118
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 119
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 120
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 121
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 122
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 123
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 124
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 125
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 126
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.541211
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.910264
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.969128
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.15519
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.52418
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.67612
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.606028
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.49095
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.06858
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.5317
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.3997
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3.50232
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.841238
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.03539
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.285899
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.34345
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 3.05438
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.74363
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.46169

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 127
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 128
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 129
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 130
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 131
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 132
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 133
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
INFO:senkin_tmp_cite_pred.lgbm_models:CV score: 0.27014975633017846
INFO:senkin_tmp_cite_pred.lgbm_models:TSVD-reducing predictions to 10 components
INFO:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model 4 for predicting raw protein expression from raw RNA expression
INFO:senkin_tmp_cite_pred.lgbm_models:Training LightGBM models for 134 targets
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 5.36667
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.3438
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.86551
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.29596
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.12275
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.02609
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.56128
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.326853
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.455104
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 0.438271
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 0.377419
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1.24437
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1.99239
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1.52369
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.28893
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 92.1374
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 145.162
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 4.12152

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 2
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 3
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 4
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 5
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 6
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 7
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 8
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 9
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 10
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 11
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 0.629158
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 439.644
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 804.945
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1727.5
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3953.29
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 36479.8
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 7991.11
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 4292.31
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4703.12
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 195.053
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 438.067
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 760.569
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2733.41
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 285.38
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 261.589
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 109.635
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 76.6482
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2064.84
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 599.408

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 12
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 13
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 14
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 15
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 16
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 17
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 18
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 19
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 20
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.21806
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 2.86357
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 28.4155
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 146.113
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 13575
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 17121
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 2427.37
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1593.42
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 784.58
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 427.704
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 13.149
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 19.6755
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 695.283
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 622.918
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 25169
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 19852.2
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 3668.58
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 202.288

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 21
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 22
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 23
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 24
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 25
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 26
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 27
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 28
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 29
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 30
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 671.46
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1744.93
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 65.212
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 309.042
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 6787.46
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 6883.06
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 505.264
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1629.13
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 125.988
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 292.439
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 11.0505
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 57.4988
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 794.773
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4512.16
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1100.76
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1379.31
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.85479
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.11221
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1589.44
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2575.19

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 31
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 32
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 33
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 34
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 35
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 36
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 37
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 38
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 39
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 3491.13
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3283.7
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 390.644
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 595.627
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2191.9
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1559.54
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 93.7078
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 117.778
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 7.08679
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 13.3649
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 8487.21
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 11903.3
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 477.036
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 542.923
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 10908.6
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 5895.22
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 6332.23
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 6935.01

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 40
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 41
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 42
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 43
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 44
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 45
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 46
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 47
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 48
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 49
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 528.256
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1096.29
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 268.692
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 473.051
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 248.792
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 583.665
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 37.953
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 78.1615
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 71.1859
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 91.0392
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 178.535
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 65.7567
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 42.303
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 50.7471
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1644.04
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4690.6
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 729.299
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2435.85
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 175.81
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 82.4584
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1355.37

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 50
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 51
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 52
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 53
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 54
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 55
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 56
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 57
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 58
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 59
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 60
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1317.6
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2330.17
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4449.79
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2832.27
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3163.93
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 9.10232
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 171.173
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 71.3118
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 74.9406
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 663.754
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 443.003
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 344.09
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 510.129
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 9829.74
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 20151.4
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 659.757
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1569.53
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 304.469
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 319.051
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1331.65
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 481.252

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 61
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 62
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 63
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 64
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 65
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 66
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 67
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 68
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 37.6333
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 122.948
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 6121.46
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 6109.45
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 49.6322
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 11.4889
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2228.28
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 2013.17
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 20.5
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 22.2216
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 118.924
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 173.156
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 186.773
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 59.0805
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 15.3302
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 23.5107
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 50.391
Training until validation scores don't improve for 2 rounds

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 69
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 70
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 71
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 72
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 73
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 74
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 75
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 76
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 77
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 99.9002
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1028.25
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2426.44
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 8.65044
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 13.5507
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 144.23
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 128.424
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 171.902
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 140.401
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 13860.1
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 9417.88
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 344.999
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 117.657
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 38.4369
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 15.5055
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 3820.11
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3132.89
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 62.0237
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 73.9049

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 78
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 79
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 80
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 81
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 82
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 83
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 84
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 85
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 86
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 87
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 120.322
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 166.364
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 16.1022
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 18.0097
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 358.706
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 282.502
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 4128.88
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 5715.47
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.237
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 13.9814
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 544.841
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 799.93
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 38.5463
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 49.0946
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 6796.28
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 10330.4
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 5047.57
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 12802.6
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 619.379

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 88
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 89
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 90
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 91
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 92
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 93
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 94
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 95
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 96
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 97
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 98
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 492.151
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 201.241
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 363.014
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 30.8249
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 60.2482
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 475.8
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 317.047
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 63.8394
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 106.33
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 113.313
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 491.215
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 51.4689
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 41.6906
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 363.409
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 489.887
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 6056.28
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1015.38
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 20.0842
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 41.8108
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 12592.8
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 7031.83

DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 99
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 100
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 101
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 102
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 103
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 104
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 105
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 106
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 107
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 108
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 10228
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 277229
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 242.193
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 338.41
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 3336.23
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2372.18
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 29.7822
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 32.5457
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 12525.5
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 15654
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2179.07
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1255.44
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 11674.9
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 5724.78
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 11.5048
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 17.6453
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 360.064
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 477.68
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 18.172
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 42.1254
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 3151.45

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 109
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 110
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 111
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 112
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 113
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 114
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 115
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 116
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 117
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 118
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 1151.01
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 117.455
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 328.037
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1372.87
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 923.091
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4.06086
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 5.28663
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 44126
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 66706.2
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 70.0941
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 81.1754
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 812.34
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 223.066
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 1004.42
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 906.973
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 2.12964
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 2.31841
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 46.6527
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 79.8639
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 25793.2
Training until validation scores don't improve for 2 rounds

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 119
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 120
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 121
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 122
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 123
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 124
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 125
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 126
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1

Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 126746
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 592.689
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 564.65
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 66.2379
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 204.681
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 12019
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 19417.8
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 2207.96
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 918.774
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 2946.78
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 8309.88
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 7.1905
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 11.7499
Training until validation scores don't improve for 2 rounds
Early stopping, best iteration is:
[1]	valid_0's l2: 320.101
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[2]	valid_0's l2: 45.9121
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 3858.02
Training until validation scores don't improve for 2 rounds

DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 127
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 128
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 129
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 130
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 131
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 132
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
DEBUG:senkin_tmp_cite_pred.lgbm_models:Training LightGBM model for target 133
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 0
DEBUG:senkin_tmp_cite_pred.lgbm_models:Fold: 1
INFO:senkin_tmp_cite_pred.lgbm_models:CV score: 0.34164555502124655
INFO:senkin_tmp_cite_pred.lgbm_models:TSVD-reducing predictions to 10 components

Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 6212.53
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 295.058
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 79.9144
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 107.99
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 47.0235
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 182.072
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 519.945
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 554791
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 6.09699e+06
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 13.4844
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 15.1919
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 4070.76
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 8821.46
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 397.978
Training until validation scores don't improve for 2 rounds
Did not meet early stopping. Best iteration is:
[3]	valid_0's l2: 1305.84

Note that we know have 4 additional `X_lgbm` arrays in the `.obsm`:

In [26]:
adata_rna

AnnData object with n_obs × n_vars = 507 × 134
    obs: 'size_factors', 'batch', 'day', 'donor', 'split', 'fold_0', 'fold_1'
    uns: 'log1p', 'selected_features'
    obsm: 'X_log_normalized', 'X_clr_tsvd', 'X_sqrt_norm', 'X_pca_sqrt_norm', 'X_raw_selected', 'X_lgbm_1', 'X_lgbm_2', 'X_lgbm_3', 'X_lgbm_4'
    layers: 'counts', 'normalized'

# Train neural networks

In [27]:
from senkin_tmp_cite_pred.nn_models import train_nn_models

Finally, we'll train two neural networks with originally proposed architectures to predict target proteins. First, let's prepare datasets:

In [28]:
train_cite_X = np.concatenate([
    adata_rna[train_cell_ids].obsm["X_clr_tsvd"],
    adata_rna[train_cell_ids].obsm["X_pca_sqrt_norm"],
    adata_rna[train_cell_ids].obsm["X_raw_selected"].toarray(),
    adata_rna[train_cell_ids].obsm["X_lgbm_1"],
    adata_rna[train_cell_ids].obsm["X_lgbm_2"],
    adata_rna[train_cell_ids].obsm["X_lgbm_3"],
    adata_rna[train_cell_ids].obsm["X_lgbm_4"],
], axis=1)

test_cite_X = np.concatenate([
    adata_rna[test_cell_ids].obsm["X_clr_tsvd"],
    adata_rna[test_cell_ids].obsm["X_pca_sqrt_norm"],
    adata_rna[test_cell_ids].obsm["X_raw_selected"].toarray(),
    adata_rna[test_cell_ids].obsm["X_lgbm_1"],
    adata_rna[test_cell_ids].obsm["X_lgbm_2"],
    adata_rna[test_cell_ids].obsm["X_lgbm_3"],
    adata_rna[test_cell_ids].obsm["X_lgbm_4"],
], axis=1)

train_cite_y = adata_prot[train_cell_ids].layers["dsb"]

In [29]:
print("Total number of features:", train_cite_X.shape[1])

Total number of features: 391

This function will perform cross-validated training and prediction, and return us aggregated prediction of two models:

In [30]:
train_preds, test_preds = train_nn_models(
    train_cell_ids,
    train_cite_X,
    train_cite_y,
    test_cell_ids,
    test_cite_X,
    folds, 
    EPOCHS=3
)

0

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 391)       │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ reshape (Reshape)   │ (None, 1, 391)    │          0 │ input_layer[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bidirectional       │ (None, 3600)      │ 23,684,400 │ reshape[0][0]     │
│ (Bidirectional)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ gaussian_dropout    │ (None, 3600)      │          0 │ bidirectional[0]… │
│ (GaussianDropout)   │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 1800)      │  6,481,800 │ gaussian_dropout… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ gaussian_dropout_1  │ (None, 1800)      │          0 │ dense[0][0]       │
│ (GaussianDropout)   │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 1800)      │  3,241,800 │ gaussian_dropout… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ gaussian_dropout_2  │ (None, 1800)      │          0 │ dense_1[0][0]     │
│ (GaussianDropout)   │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate         │ (None, 7200)      │          0 │ gaussian_dropout… │
│ (Concatenate)       │                   │            │ gaussian_dropout… │
│                     │                   │            │ gaussian_dropout… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 134)       │    964,934 │ concatenate[0][0] │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 34,372,934 (131.12 MB)

 Trainable params: 34,372,934 (131.12 MB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/3
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 4s/step - loss: 0.0000e+00

DEBUG:h5py._conv:Creating converter from 5 to 3

1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step - loss: 0.0000e+00 - val_loss: -0.2863 - learning_rate: 0.0010
Epoch 2/3
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 326ms/step - loss: -0.3422 - val_loss: -0.1132 - learning_rate: 0.0010
Epoch 3/3
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 237ms/step - loss: -0.1432 - val_loss: -0.2682 - learning_rate: 0.0010
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 389ms/step
[np.float64(0.2862512015140049)]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 334ms/step
1

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 391)       │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ reshape (Reshape)   │ (None, 1, 391)    │          0 │ input_layer[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bidirectional       │ (None, 3600)      │ 23,684,400 │ reshape[0][0]     │
│ (Bidirectional)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ gaussian_dropout    │ (None, 3600)      │          0 │ bidirectional[0]… │
│ (GaussianDropout)   │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 1800)      │  6,481,800 │ gaussian_dropout… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ gaussian_dropout_1  │ (None, 1800)      │          0 │ dense[0][0]       │
│ (GaussianDropout)   │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 1800)      │  3,241,800 │ gaussian_dropout… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ gaussian_dropout_2  │ (None, 1800)      │          0 │ dense_1[0][0]     │
│ (GaussianDropout)   │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate         │ (None, 7200)      │          0 │ gaussian_dropout… │
│ (Concatenate)       │                   │            │ gaussian_dropout… │
│                     │                   │            │ gaussian_dropout… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 134)       │    964,934 │ concatenate[0][0] │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 34,372,934 (131.12 MB)

 Trainable params: 34,372,934 (131.12 MB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/3
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step - loss: 0.0000e+00 - val_loss: -0.3038 - learning_rate: 0.0010
Epoch 2/3
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step - loss: -0.3267 - val_loss: -0.1529 - learning_rate: 0.0010
Epoch 3/3
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step - loss: -0.1670 - val_loss: -0.2719 - learning_rate: 0.0010
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 282ms/step
[np.float64(0.2862512015140049), np.float64(0.30377504156477475)]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 305ms/step
Overall: 0.2949883002362017
0

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 391)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1500)           │       588,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gaussian_dropout                │ (None, 1500)           │             0 │
│ (GaussianDropout)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1500)           │     2,251,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gaussian_dropout_1              │ (None, 1500)           │             0 │
│ (GaussianDropout)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1500)           │     2,251,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gaussian_dropout_2              │ (None, 1500)           │             0 │
│ (GaussianDropout)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ reshape (Reshape)               │ (None, 1, 1500)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 1400)           │     9,248,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gaussian_dropout_3              │ (None, 1400)           │             0 │
│ (GaussianDropout)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 134)            │       187,734 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 14,527,134 (55.42 MB)

 Trainable params: 14,527,134 (55.42 MB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/3
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 4s/step - loss: 6.4502WARNING:tensorflow:5 out of the last 13 calls to <function TensorFlowTrainer._make_function.<locals>.multi_step_on_iterator at 0x32004b100> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

WARNING:tensorflow:5 out of the last 13 calls to <function TensorFlowTrainer._make_function.<locals>.multi_step_on_iterator at 0x32004b100> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step - loss: 6.4502 - val_loss: 28.6896 - learning_rate: 5.0000e-04
Epoch 2/3
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 691ms/step - loss: 7.7774 - val_loss: 4.6671 - learning_rate: 5.0000e-04
Epoch 3/3
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 571ms/step - loss: 1.9764 - val_loss: 2.6172 - learning_rate: 5.0000e-04
WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x321887ba0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x321887ba0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 297ms/step
[np.float64(0.045899770372618394)]
WARNING:tensorflow:6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x321887ba0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

WARNING:tensorflow:6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x321887ba0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 304ms/step
1

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 391)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1500)           │       588,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gaussian_dropout                │ (None, 1500)           │             0 │
│ (GaussianDropout)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1500)           │     2,251,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gaussian_dropout_1              │ (None, 1500)           │             0 │
│ (GaussianDropout)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1500)           │     2,251,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gaussian_dropout_2              │ (None, 1500)           │             0 │
│ (GaussianDropout)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ reshape (Reshape)               │ (None, 1, 1500)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 1400)           │     9,248,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gaussian_dropout_3              │ (None, 1400)           │             0 │
│ (GaussianDropout)               │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 134)            │       187,734 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 14,527,134 (55.42 MB)

 Trainable params: 14,527,134 (55.42 MB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/3
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 4s/step - loss: 26.7986WARNING:tensorflow:5 out of the last 13 calls to <function TensorFlowTrainer._make_function.<locals>.multi_step_on_iterator at 0x2d31da7a0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

WARNING:tensorflow:5 out of the last 13 calls to <function TensorFlowTrainer._make_function.<locals>.multi_step_on_iterator at 0x2d31da7a0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step - loss: 26.7986 - val_loss: 5.9460 - learning_rate: 5.0000e-04
Epoch 2/3
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 526ms/step - loss: 34.8100 - val_loss: 1.4675 - learning_rate: 5.0000e-04
Epoch 3/3
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 395ms/step - loss: 6.0340 - val_loss: 1.2064 - learning_rate: 5.0000e-04
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 328ms/step
[np.float64(0.045899770372618394), np.float64(0.039506947185528926)]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 334ms/step
Overall: 0.042712413769423634
Blend: 0.23579725593598302

Because for this dataset we know the ground truth, we can compute the correlation score for test data:

In [31]:
from senkin_tmp_cite_pred.metrics import correlation_score

In [32]:
correlation_score(adata_prot[test_cell_ids].layers["dsb"], test_preds)

np.float64(0.1572785361512277)